import { jsPDF } from "jspdf";

export default function ExportButton({ decision, agentResults, consensus, decisionType }) {
  const handleExport = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    const addText = (text, size, color, bold) => {
      doc.setFontSize(size);
      doc.setTextColor(...color);
      if (bold) doc.setFont("helvetica", "bold");
      else doc.setFont("helvetica", "normal");

      const lines = doc.splitTextToSize(text, maxWidth);
      lines.forEach((line) => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(line, margin, y);
        y += size * 0.5;
      });
      y += 3;
    };

    const addDivider = () => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setDrawColor(50, 50, 80);
      doc.line(margin, y, pageWidth - margin, y);
      y += 6;
    };

    // Title
    addText("SHADOW BOARD", 22, [99, 102, 241], true);
    addText("Multi-Agent AI Advisory Report", 11, [148, 163, 184], false);
    addText(`Date: ${new Date().toLocaleDateString("en-IN")}`, 9, [100, 116, 139], false);
    addText(`Decision Type: ${decisionType.toUpperCase()}`, 9, [100, 116, 139], false);
    y += 4;
    addDivider();

    // Decision
    addText("DECISION ANALYZED", 11, [99, 102, 241], true);
    addText(decision, 10, [203, 213, 225], false);
    y += 4;
    addDivider();

    // Each agent
    const agentColors = {
      risk:      [239, 68,  68 ],
      growth:    [34,  197, 94 ],
      financial: [59,  130, 246],
      devil:     [245, 158, 11 ],
    };

    agentResults.forEach((agent) => {
      const color = agentColors[agent.id] || [148, 163, 184];
      addText(`${agent.emoji} ${agent.name.toUpperCase()}`, 12, color, true);
      addText(agent.content, 9, [148, 163, 184], false);
      y += 4;
      addDivider();
    });

    // Consensus
    addText("⚪ CONSENSUS SUMMARY", 12, [168, 85, 247], true);
    addText(consensus, 9, [203, 213, 225], false);

    // Footer
    y += 10;
    addDivider();
    addText("Generated by Shadow Board — Multi-Agent AI Advisory System", 8, [71, 85, 105], false);

    doc.save(`shadow-board-report-${Date.now()}.pdf`);
  };

  return (
    <button
      onClick={handleExport}
      style={{
        marginTop: "1.5rem", width: "100%",
        padding: "0.9rem", borderRadius: "14px",
        background: "linear-gradient(135deg, #7c3aed, #6d28d9)",
        color: "#fff", border: "none", cursor: "pointer",
        fontSize: "0.95rem", fontWeight: "600",
        fontFamily: "Inter, sans-serif",
        boxShadow: "0 4px 15px rgba(124,58,237,0.3)",
        transition: "all 0.2s",
        letterSpacing: "0.02em"
      }}
      onMouseOver={(e) => e.target.style.transform = "translateY(-1px)"}
      onMouseOut={(e) => e.target.style.transform = "translateY(0)"}
    >
      📄 Download PDF Report
    </button>
  );
}